### ISSUE TITLE
Migrate to IntelliJ-jdk

### ISSUE THREAD

**Issue by sodre** [conda-forge/openjdk-feedstock#14]
Moving the sidebar convo from #13  here.

It looks there are only upsides to moving to Intellij-jdk, including closing #12 .

@mingwandroid, would you like to start the process?

**Comment by mingwandroid** [comment]
I'm busy until AD 5 is out and then I'm taking a holiday for a week, but after that I'll bring it up with @csoja and see if I can mak a start on this. Feel free to jump in though if you have time.

One thing to be careful about before committing to this course of action is to make sure there are no files that overlap with `conda-forge` packages (though I'm not sure we know that isn't the case with Azul's openjdk anyway). If there is overlap we can probably use `install_name_tool` and `patchelf` to workaround them on macOS and Linux, but Windows may be trickier.
