### ISSUE TITLE
track_features openjdk

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/openjdk-feedstock#37]
Appears this is using `track_features`. Why is that? Also should it be using `track_features` or something else to achieve that goal?

https://github.com/conda-forge/openjdk-feedstock/blob/f16da873a578a6b2690cb3ccd1ebaccbea48418e/recipe/meta.yaml#L30-L31

**Comment by sodre** [comment]
I think this was so we could use different JDK implementations.

**Comment by sodre** [comment]
Okay, in that case I will remove the track-features set if it is okay with you.

**Comment by jakirkham** [comment]
Sounds good.

To clarify a bit, the mutex package uses `track_features` to indicate all non-default builds of a package as it relies on Conda's desire to minimize features. For example we might have `openjdk` from different vendors (Zulu, IntelliJ, etc.). If we picked one vendor build as the preferred `openjdk` (e.g. IntelliJ), then we would add `track_features` to all of the non-default builds (e.g. Zulu, etc.). These would all live in the same feedstock and all be called `openjdk`.
