### ISSUE TITLE
Using compiler in test phase

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/openjdk-feedstock#41]
As the test phase of the recipe is making use of a C compiler for JNI testing, it would be good to use the [compiler syntax]( https://conda-forge.org/docs/meta.html#compilers ) to require one and update the test to be a bit more general about the compiler used. Should help make sure that JNI works nicely with the compilers we use to build other packages (including those that will make use of JNI).

**Comment by sodre** [comment]
I tried to add the compiler tag only to the test section but the .ci_support files did not get generated correctly. Instead of creating entries for linux and osx it only generated them for windows.

**Comment by sodre** [comment]
Here is the commit of the regenerated support files.

https://github.com/conda-forge/openjdk-feedstock/pull/35/commits/cbbf38ffcfde8af52f865ae1a3ecfcf3686c40ae

**Comment by jakirkham** [comment]
Perfect. Was just about to ask for that.

Can you please raise an issue on the `conda-smithy` issue tracker linking that and the previous commit with some explanation of what is (and should be) happening?

**Comment by sodre** [comment]
I was expecting the gcc7 and toolchain variants for linux. Maybe that will get picked up by the bot later..

**Comment by jakirkham** [comment]
Ah ok. Yeah, that's correct. The bot will take care of that afterwards.
