### ISSUE TITLE
set JAVA_HOME?

### ISSUE THREAD

**Issue by croth1** [conda-forge/openjdk-feedstock#5]
Should this recipe also set the JAVA_HOME environment variables?

**Comment by johanneskoester** [comment]
I thought it does... See the activate scripts.

**Comment by croth1** [comment]
uh sorry, missed that. Then r-java has some other weird problem 👎

**Comment by astrojuanlu** [comment]
Unless you're on another shell, see https://github.com/conda/conda/issues/7993

**Comment by h-vetinari** [comment]
This issue has been dead for 7 years. If there are still problems, please open a new issue (though it's great that you checked, and by all means, refer to historical precedents!)
