### ISSUE TITLE
openjdk-11 broken on mulled builds

### ISSUE THREAD

**Issue by Lenbok** [conda-forge/openjdk-feedstock#55]
Issue:

Over in bioconda I am trying to update the recipe for a package that requires java (rtg-tools) See https://github.com/bioconda/bioconda-recipes/pull/13144#issuecomment-456281150. The software itself has been tested under Java 11, however the bioconda CI system fails to run the package tests when running in their "mulled-tests" environment that has minimal extra packages installed in the base image. It turns out that the openjdk-11 which is pulled in from conda-forge as a prerequisite is broken in that environment (i.e. java -help crashes) due to no zlib. Adding an explicit zlib requirement to the rtg-tools dependencies makes things work, but it seems that the correct thing is to have the openjdk package require zlib. I was requested by @bgruening to open an issue here.

**Comment by isuruf** [comment]
Fixed in #56
