### ISSUE TITLE
package clobbers libfreetype.so

### ISSUE THREAD

**Issue by jschueller** [conda-forge/openjdk-feedstock#59]
this package contains a ```$PREFIX/lib/libfreetype.so``` which conflicts with the freetype package
  (conda-forge::freetype-2.10.0-he983fc9_0)
```
2019-05-11T06:01:06.3195692Z ClobberWarning: This transaction has incompatible packages due to a shared path.
2019-05-11T06:01:06.3196968Z   packages: conda-forge::openjdk-11.0.1-h516909a_1016, conda-forge::freetype-2.10.0-he983fc9_0
2019-05-11T06:01:06.3197719Z   path: 'lib/libfreetype.so'
```

maybe it could be removed so to depend on freetype, or libs moved to ```$PREFIX/lib/jvm``` ?

**Comment by isuruf** [comment]
ping

**Comment by jakirkham** [comment]
Am still seeing this on Windows:

```
ClobberWarning: This transaction has incompatible packages due to a shared path.
  packages: conda-forge/win-64::openjdk-11.0.1-c_compilervs2015_1016, conda-forge/win-64::freetype-2.10.4-h546665d_1
  path: 'library/bin/freetype.dll'
```

Relevant [CI run]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=408933&view=logs&j=8cde0db1-5207-5e76-f495-971492850bfd&t=8b12ef46-7a11-53d2-7d05-e3b0b262b4c2 ) and [attached log]( https://github.com/conda-forge/openjdk-feedstock/files/7517010/dask-sql_20211110_6__win_64_python3.9.____cpython.txt ) (for posterity)

**Comment by h-vetinari** [comment]
Not seeing this issue anymore. I checked the package content, and `freetype.dll` now has another path:
```
Library/lib/jvm/bin/freetype.dll
```

I believe this is a consequence of #100 (resp. its backport to `java11`, #105). Closing.
