### ISSUE TITLE
Support more recent bugfix (jdk-11.0.6)

### ISSUE THREAD

**Issue by fabiencelier** [conda-forge/openjdk-feedstock#65]
Hello,

The latest release of the conda package is 11.0.2 while on AdoptOpenJDK there is [11.0.6](https://adoptopenjdk.net/?variant=openjdk11&jvmVariant=hotspot) available. Are you planning to release these new versions ?

**Comment by msarahan** [comment]
Closing; current version available is 11.0.9: https://github.com/conda-forge/openjdk-feedstock/blob/1e355f1a208b7bbc63b384e9680a29a439d1eab5/recipe/meta.yaml#L2

**Comment by fabiencelier** [comment]
Thank you
