### ISSUE TITLE
OpenJDK 11.0.4?

### ISSUE THREAD

**Issue by Juke34** [conda-forge/openjdk-feedstock#72]
Would it be possible to update openjdk to version 11.0.4? The current available one is 11.0.1.
@mingwandroid
@sodre
@hadim
@johanneskoester

**Comment by msarahan** [comment]
closing; current version is 11.0.9: https://github.com/conda-forge/openjdk-feedstock/blob/1e355f1a208b7bbc63b384e9680a29a439d1eab5/recipe/meta.yaml#L2
