### ISSUE TITLE
How to generalise recipes for all major OpenJDK update? 

### ISSUE THREAD

**Issue by serine** [conda-forge/openjdk-feedstock#82]
- [x] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I'd like to `conda install -c conda-forge openjdk >= 12`

Looking at the [recipe](https://github.com/conda-forge/openjdk-feedstock/blob/master/recipe/meta.yaml) it seems that it's hardcoded for version 11 only (the binaries are pulled from `AdoptOpenJDK/openjdk11-binaries`)

In my attempt to fork and edit the recipe I stuck at trying to figure out the need of pulling another set of binaries? from https://hg.openjdk.java.net/jdk-updates/jdk11u/tags and the mapping of versions between https://github.com/AdoptOpenJDK/openjdk15-binaries/releases and https://hg.openjdk.java.net/jdk-updates/jdk15u/tags. It appeared to me that it was difficult to generalise both via `version` string?

**Comment by h-vetinari** [comment]
Closing this issue as outdated. We're building Java 17, 20 (and soon 21), and the recipe is now also not hardcoding the versions in the URLs anymore.
