### ISSUE TITLE
OpenJDK JDK 18 GA Release

### ISSUE THREAD

**Issue by XhstormR** [conda-forge/openjdk-feedstock#92]
### Comment:

Hello team,  jdk 18 is out.

https://jdk.java.net/18/

https://github.com/openjdk/jdk/releases/tag/jdk-18-ga

**Comment by richard-burhans** [comment]
I have an untested java 18 branch on my [fork](https://github.com/richard-burhans/openjdk-feedstock/tree/java18)

**Comment by bernt-matthias** [comment]
Seems to be outdated according to the link in the issue. Anyway, an update would be very welcome.

**Comment by XhstormR** [comment]
It's jdk 20 now, but we're still at 17.

**Comment by h-vetinari** [comment]
In fact, we're only on LTS versions (almost exclusively; there can be and have been exceptions). Next LTS is 21.

Hilariously, lots of key java libraries (like Hadoop) are still not even on java 11...

**Comment by bernt-matthias** [comment]
Thanks for this insights in the Java ecosystem. From the past changes and the branch for release 18 that has been mentioned above, it seems that an update might  be as simple as just updating a few links? ... But it seems to require some knowledge of all the components that seem to be involved. 

For me it would be cool to have anything `>=19`.. which is what a software that I try to integrate into bioconda requires.

Maybe branches for the LTS releases are an option, and main may be more up to date? Or would this be overkill.

**Comment by h-vetinari** [comment]
You can open a PR that tries to update the recipe to JDK 19 or 20, and we take it from there.

**Comment by bernt-matthias** [comment]
I will first try if the project I want to add could be convinced to support LTS OpenJDK. I actually like the idea of only having LTS versions in conda (based on a vague and likely wrong intuition).

**Comment by bernt-matthias** [comment]
OK. Seems not to be possible for the project to go back to 17. So lets see if we can update conda-forge openjdk https://github.com/conda-forge/openjdk-feedstock/pull/118

**Comment by bernt-matthias** [comment]
Made a bit of progress but fail to get it running for `aarch64`. Would appreciate any help / comments: https://github.com/conda-forge/openjdk-feedstock/pull/118

The test (`javac`) produces a core dump. If I got my debugging right it might be a OOM problem .. would not surprise me (java's memory management bugs me for years .. I have a hard time to not start a rant :) .. but I might be wrong).

**Comment by bernt-matthias** [comment]
FYI 20 is out.
